name: CI Bancolombia Saldo Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Ejecutar Pruebas Unitarias
        run: |
          python -m unittest test_saldo.py

      - name: Construir Imagen Docker
        run: |
          docker build -t saldo-service:${{ github.sha }} .